[project]
name = "speedtest-exporter"
version = "1.1.0"
description = "Yet another Speedtest.net exporter for Prometheus"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.2",
    "gunicorn>=23.0.0",
    "ruff>=0.12.12",
]
